### ISSUE TITLE
multi-line commit message has quotes

### ISSUE THREAD

**Issue by yelizariev** [matheusalbino/git-commit#1]
I have the following [setup](https://github.com/it-projects-llc/odoo-test/blob/master/.github/workflows/main.yml):

    - uses: matheusalbino/git-commit@v1.0.0
      name: Commit updates
      with:
        user-name: Mitchell Admin (from Github Actions)
        user-email: itpp-bot@it-projects.info
        message: |
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/main.yml )

The commit message I see in github is surrounded by douple quotes:

https://github.com/it-projects-llc/odoo-test/commit/1ddc015278656516d223e74a672035b389488046

Any idea how to avoid that?

**Comment by matheusalbino** [comment]
@yelizariev thanks for using this Github Action!

I will make tests to analyze this case.

**Comment by matheusalbino** [comment]
@yelizariev I release the new version of this Github Action.

This bug occurred in two cases, multi-line and single-line. Thanks for reporting this bug!

You can use the new version `v1.0.1`:
```yml
- uses: matheusalbino/git-commit@v1.0.1
  name: Commit updates
  with:
    user-name: Mitchell Admin (from Github Actions)
    user-email: itpp-bot@it-projects.info
    message: |
      :alien: recompile docs
      
      Sent from Github Actions (see .github/workflows/main.yml )
```
