### ISSUE TITLE
Always pushes to master

### ISSUE THREAD

**Issue by yelizariev** [matheusalbino/git-commit#2]
It's not only a feature request to support committing to non-master branch, but this also a bug report.

I made a [PR](https://github.com/it-projects-llc/odoo-saas/pull/11) from a branch of the same repo to master branch. I have a plain [config](https://github.com/it-projects-llc/odoo-saas/blob/master/.github/workflows/main.yml) with ``on: [push]`` trigger. 

What do I expect:
* the workflow will run when PR is merged

What do I get:
* PR is merged immediately after creating

**Comment by matheusalbino** [comment]
@yelizariev This configuration will execute in every push not exactly when the PR is merged.

Try to use this configuration:
```yaml
on:
  pull_request:
    types: [ closed ]
    
jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
```
